// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview This file defines a Genkit flow for categorizing herbs based on their medicinal properties, cultivation methods, and preservation techniques.
 *
 * The flow takes an herb name as input and returns a categorization of the herb.
 *
 * @file            categorize-herb-flow.ts
 * @exports       categorizeHerb
 * @exports       CategorizeHerbInput
 * @exports       CategorizeHerbOutput
 */

import {ai} from '@/app/ai/genkit';
import {z} from 'genkit';

const CategorizeHerbInputSchema = z.object({
  herbName: z.string().describe('The common name of the herb to categorize.'),
});

export type CategorizeHerbInput = z.infer<typeof CategorizeHerbInputSchema>;

const CategorizeHerbOutputSchema = z.object({
  medicinalProperties: z.string().describe('The medicinal properties of the herb.'),
  cultivationMethods: z.string().describe('The cultivation methods for the herb.'),
  preservationTechniques: z.string().describe('The preservation techniques for the herb.'),
  category: z.string().describe('The overall category of the herb based on the above properties.'),
});

export type CategorizeHerbOutput = z.infer<typeof CategorizeHerbOutputSchema>;

/**
 * Categorizes an herb based on its medicinal properties, cultivation methods, and preservation techniques.
 * @param input - The input object containing the herb's name.
 * @returns A promise that resolves to an object containing the herb's categorization.
 */
export async function categorizeHerb(input: CategorizeHerbInput): Promise<CategorizeHerbOutput> {
  return categorizeHerbFlow(input);
}

const categorizeHerbPrompt = ai.definePrompt({
  name: 'categorizeHerbPrompt',
  input: {schema: CategorizeHerbInputSchema},
  output: {schema: CategorizeHerbOutputSchema},
  prompt: `You are an expert in herbal medicine and botany. Given the name of an herb, provide a detailed categorization based on its medicinal properties, cultivation methods, and preservation techniques.

  Herb Name: {{{herbName}}}

  Consider the following aspects when categorizing the herb:
  - Medicinal Properties: What are the primary medicinal uses of this herb? What conditions can it treat or alleviate?
  - Cultivation Methods: How is this herb typically grown? What are the ideal growing conditions (e.g., sunlight, soil type, climate)?
  - Preservation Techniques: How can this herb be best preserved to maintain its potency and freshness (e.g., drying, freezing, tincturing)?
  - Category: Provide a general category for this herb, summarizing its key characteristics and uses.

  Please provide your categorization in a structured format, covering all the aspects mentioned above.
`,
});

const categorizeHerbFlow = ai.defineFlow(
  {
    name: 'categorizeHerbFlow',
    inputSchema: CategorizeHerbInputSchema,
    outputSchema: CategorizeHerbOutputSchema,
  },
  async input => {
    const {output} = await categorizeHerbPrompt(input);
    return output!;
  }
);
